env: local  
db: 
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: taskmanager
  migrations_path: /etc/taskmanager/migrations
http_server:  
  port: :8080 
  timeout: 10s
  idle_timeout: 120s
health_check:
  port: :8000
telemetry:
  port: :9090
auth:
  kratos_ip: kratos
  hydra_ip: hydra
  ui_ip: 127.0.0.1
  scopes: "openid,offline,tasks:read,tasks:create,tasks:update,tasks:delete"