version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   # HTTP server
      - "8000:8000"   # Health check
      - "9090:9090"   # Metrics
    depends_on:
      - db
    volumes:
      - ./internal/config/config_docker.yaml:/etc/config.yaml
    environment:
      - GODEBUG=gctrace=1 # Enable GC trace
    networks:
      - taskmanager-net

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # !!! Сменить пароль !!!
      POSTGRES_DB: taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-net

  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9000:9090"
    networks:
      - taskmanager-net

volumes:
  postgres_data:
  prometheus_data:

networks:
  taskmanager-net:
    driver: bridge