global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'taskmanager'
    static_configs:
      - targets: ['server:9090']
        labels:
          application: 'taskmanager-server'