apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "taskmanager.fullname" . }}-config
    labels:
        {{- include "taskmanager.labels" . | nindent 8 }}
data:
    config.yaml: |
        {{- toYaml .Values.config | nindent 16 }}