apiVersion: v1
kind: Secret
metadata:
    name: {{ include "taskmanager.fullname" . }}-secret
    labels:
        {{- include "taskmanager.labels" . | nindent 8 }}
type: Opaque
stringData:
    db_user: {{ .Values.config.db.user | quote }}
    db_password: {{ .Values.config.db.password | quote }}
    db_name: {{ .Values.config.db.name | quote }}