apiVersion: v1
kind: Service
metadata:
    name: {{ include "taskmanager.fullname" . }}
    labels:
        {{- include "taskmanager.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
        {{- if eq .Values.service.type "LoadBalancer" }}
          nodePort: {{ .Values.service.nodePort }} # Only set nodePort if type is NodePort
        {{- end }}
    selector:
        {{- include "taskmanager.selectorLabels" . | nindent 8 }}