apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
data:
  config.yaml: |
    env: local
    db: 
      host: taskmanager-db
      port: 5432
      user: postgres
      password: postgres
      name: taskmanager
    http_server:  
      port: :8080
      timeout: 10s
      idle_timeout: 120s
    health_check:
      port: :8000
    telemetry:
      port: :9090