# This file contains the deployment configuration for the Postgres database.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskmanager-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
--- # Deployment for Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-db
spec:
  selector:
    matchLabels:
      app: taskmanager-db
  replicas: 1
  template:
    metadata:
      labels:
        app: taskmanager-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: db_user 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: db_name
          volumeMounts:
            - name: postgres-data-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: taskmanager-db-pvc
--- # Service for Postgres
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: taskmanager-db