# This file contains the deployment configuration for the TaskManager server.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  labels:
    app: taskmanager
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z -v -w30 taskmanager-db 5432; do
              echo "Waiting for PostgreSQL to become available..."
              sleep 2
            done
            echo "PostgreSQL is ready!"
      containers:
        - name: taskmanager-server
          image: taskmanager-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/taskmanager
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
               path: /health
               port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: taskmanager-config
--- # Service for TaskManager
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer