env: "local"  
db: 
  host: "db"  
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "taskmanager"  
http_server:  
  port: ":8080"  
  timeout: 10s
  idle_timeout: 120s
telemetry:
  port: 8000