# Default values for Kratos.
image:
  repository: oryd/kratos
  tag: v1.3.0  
  pullPolicy: IfNotPresent

config: | 
  version: v1.3.0
  dsn: postgres://postgres:postgres@kratos-db:5432/kratos?sslmode=disable
  serve:
    public:
      base_url: http://127.0.0.1:4433
      cors:
        enabled: true
    admin:
      base_url: http://127.0.0.1:4434

  selfservice:
    default_browser_return_url: http://127.0.0.1:4455/
    allowed_return_urls:
      - http://127.0.0.1:4455

    methods:
      password:
        enabled: true
        config:
          min_password_length: 6
          identifier_similarity_check_enabled: false
          haveibeenpwned_enabled: false

    flows:
      error:
        ui_url: http://127.0.0.1:4455/error
      settings:
        ui_url: http://127.0.0.1:4455/settings
        privileged_session_max_age: 15m
        required_aal: highest_available
      logout:
        after:
          default_browser_return_url: http://127.0.0.1:4455/login
      login:
        ui_url: http://127.0.0.1:4455/login
      registration:
        ui_url: http://127.0.0.1:4455/registration
        after:
          password:
            hooks:
              - hook: web_hook
                config:
                  url: http://server:8080/webhooks/kratos
                  method: POST
                  body: file:///etc/config/kratos/registration-webhook.jsonnet
              - hook: session

  log:
    format: text
    leak_sensitive_values: true

  secrets:
    cookie:
      - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
    cipher:
      - 32-LONG-SECRET-NOT-SECURE-AT-ALL

  identity:
    default_schema_id: default
    schemas: 
      - id: default
        url: file:///etc/config/kratos/identity.schema.json

  courier:
    smtp:
      connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true


identitySchema: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }


persistence:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres 
    database: kratos

service:
  type: ClusterIP
  publicPort: 4433
  adminPort: 4434

resources: {}
limits:
  cpu: 100m
  memory: 128Mi
requests:
  cpu: 100m
  memory: 128Mi

extraEnvVars: [] 

extraVolumeMounts: [] 

extraVolumes: [] 

readinessProbe: # Add readiness probe.
  httpGet:
    path: /.well-known/kratos/public/health/ready
    scheme: HTTP
    port: 4433
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
livenessProbe: # Add liveness probe.
  httpGet:
    path: /.well-known/kratos/public/health/alive
    scheme: HTTP
    port: 4433
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3