 apiVersion: v1
 kind: ConfigMap
 metadata:
    name: {{ include "kratos.fullname" . }}-config
    labels:
        {{- include "kratos.labels" . | nindent 8 }}
 data:
    kratos.yaml: |
        {{- .Values.config | nindent 12 }}
    identity.schema.json: |
        {{- .Values.identitySchema | nindent 12 }}