apiVersion: v1
kind: Service
metadata:
    name: {{ include "kratos.fullname" . }}
    labels:
        {{- include "kratos.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.publicPort }}
          targetPort: public 
          protocol: TCP
          name: public
        - port: {{ .Values.service.adminPort }}
          targetPort: admin
          protocol: TCP
          name: admin
    selector:
        {{- include "kratos.selectorLabels" . | nindent 8 }}